In [1]:
import pandas as pd
import numpy as np

C:\Users\Lakshman Kishore\AppData\Local\Temp\ipykernel_18624\2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Pandas Data Structure and Operation


### Series

In [2]:
#  The Series is the object of the pandas library designed to represent one-dimensional data structures

In [3]:
s = pd.Series([12,-4,7,9])

In [4]:
s

0    12
1    -4
2     7
3     9
dtype: int64

In [5]:
# If you do not specify any index during the definition of the Series, by default, pandas will assign 
# numerical values increasing from 0 as labels.

In [6]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'])

In [7]:
s

a    12
b    -4
c     7
d     9
dtype: int64

In [8]:
s.values

array([12, -4,  7,  9], dtype=int64)

In [9]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
s[2]

C:\Users\Lakshman Kishore\AppData\Local\Temp\ipykernel_18624\2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]


7

In [11]:
s['b']

-4

In [12]:
s[0:2]

a    12
b    -4
dtype: int64

In [13]:
s[['b','c']]

b   -4
c    7
dtype: int64

In [14]:
# How are indexes helpful?
# 1. Label-Based Access: When using the index, you can easily perform label-based access using .loc[] or .iloc[] methods.
# 2. Alignment of Data: Operations between two DataFrames or between a DataFrame and a Series automatically align based on the index
# 3. Efficient Merging and Joining: When merging or joining DataFrames, you can specify the index as the key for the operation, which can be more efficient than using regular columns.
# 4. Resampling and Frequency Conversion: The index plays a crucial role in time-related operations, such as resampling and frequency conversion. Pandas has dedicated functions like resample that work seamlessly with time-based indices.
# 5. Multi-level Indexing: Pandas supports multi-level indexing, allowing you to create hierarchical indices.

# While you can certainly perform aggregations on a regular column, using the index can often lead to more concise, readable, and efficient code, especially in the context of time-series data and when performing operations involving multiple DataFrames. It provides a structured and powerful way to organize and manipulate data in pandas.

In [15]:
s[1] = 0

C:\Users\Lakshman Kishore\AppData\Local\Temp\ipykernel_18624\2737726826.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s[1] = 0


In [16]:
s

a    12
b     0
c     7
d     9
dtype: int64

In [17]:
s['b'] = 1

In [18]:
s

a    12
b     1
c     7
d     9
dtype: int64

In [19]:
#  You can define new Series starting with NumPy arrays or existing Series.

In [20]:
arr = np.array([1,2,3,4])

In [21]:
s3 = pd.Series(arr)

In [22]:
s3

0    1
1    2
2    3
3    4
dtype: int32

In [23]:
# Filtering the values
s[s>8]

a    12
d     9
dtype: int64

In [24]:
s/2

a    6.0
b    0.5
c    3.5
d    4.5
dtype: float64

In [25]:
np.log(s)

a    2.484907
b    0.000000
c    1.945910
d    2.197225
dtype: float64

In [26]:
serd = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])

In [27]:
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [28]:
serd.unique()

array([1, 0, 2, 3], dtype=int64)

In [29]:
serd.value_counts()

1    2
2    2
0    1
3    1
Name: count, dtype: int64

In [30]:
serd.isin([0,3])

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool

In [31]:
# Filtering the rows
serd[serd.isin([0,3])]

white     0
yellow    3
dtype: int64

In [32]:
# NaN values -> NaN - Not a Number
# This specific value NaN (Not a Number) is used within pandas data structures to indicate the 
# presence of an empty field or not definable numerically.

In [33]:
s2 = pd.Series([5,-3,np.NaN,14])

In [34]:
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [35]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [36]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [37]:
mydict = {'red': 2000, 'blue': 1000, 'yellow': 500, 'orange': 1000}

In [38]:
myseries = pd.Series(mydict)

In [39]:
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [40]:
mydict2 = {'red':400,'yellow':1000,'black':700}

In [41]:
myseries2 = pd.Series(mydict2)

In [42]:
myseries2

red        400
yellow    1000
black      700
dtype: int64

In [43]:
myseries + myseries2

black        NaN
blue         NaN
orange       NaN
red       2400.0
yellow    1500.0
dtype: float64

### DataFrame

In [44]:
# The DataFrame is a tabular data structure very similar to the Spreadsheet 
# This data structure is designed to extend the case of the Series to multiple dimensions.

In [45]:
data = {'color' : ['blue','green','yellow','red','white'],
                     'object' : ['ball','pen','pencil','paper','mug'],
                     'price' : [1.2,1.0,0.6,0.9,1.7]}

In [46]:
frame = pd.DataFrame(data)

In [47]:
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [48]:
frame2 = pd.DataFrame(data, columns=['object','price'])

In [49]:
frame2

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [50]:
frame2 = pd.DataFrame(data, index=['one','two','three','four','five'])

In [51]:
frame2

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [52]:
frame3 = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper']) 

In [53]:
frame3

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [54]:
frame.columns

Index(['color', 'object', 'price'], dtype='object')

In [55]:
frame['price']

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [56]:
frame.price

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [57]:
frame.iloc[2]

color     yellow
object    pencil
price        0.6
Name: 2, dtype: object

In [58]:
# gives 0th to 1st row data, same as slicing the list
frame[0:2]

color object  price
0   blue   ball    1.2
1  green    pen    1.0

In [59]:
frame[1:4]

color  object  price
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9

In [60]:
frame['object'][3]

'paper'

In [61]:
frame.index.name = 'id'
frame.columns.name = 'item'

In [62]:
frame

item   color  object  price
id                         
0       blue    ball    1.2
1      green     pen    1.0
2     yellow  pencil    0.6
3        red   paper    0.9
4      white     mug    1.7

In [63]:
frame['new'] = 12
# Careful with the initalization, this will replace all the records with the value

In [64]:
frame

item   color  object  price  new
id                              
0       blue    ball    1.2   12
1      green     pen    1.0   12
2     yellow  pencil    0.6   12
3        red   paper    0.9   12
4      white     mug    1.7   12

In [65]:
frame['new'] = [3.0,1.3,2.2,0.8,1.1]

In [66]:
frame

item   color  object  price  new
id                              
0       blue    ball    1.2  3.0
1      green     pen    1.0  1.3
2     yellow  pencil    0.6  2.2
3        red   paper    0.9  0.8
4      white     mug    1.7  1.1

In [67]:
ser = pd.Series(np.arange(5))

In [68]:
ser

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [69]:
frame["new"] = ser

In [70]:
frame

item   color  object  price  new
id                              
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil    0.6    2
3        red   paper    0.9    3
4      white     mug    1.7    4

In [71]:
frame

item   color  object  price  new
id                              
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil    0.6    2
3        red   paper    0.9    3
4      white     mug    1.7    4

In [72]:
frame.isin([1.0,'pen'])

item  color  object  price    new
id                               
0     False   False  False  False
1     False    True   True   True
2     False   False  False  False
3     False   False  False  False
4     False   False  False  False

In [73]:
frame[frame.isin([1.0,'pen'])]

item color object  price  new
id                           
0      NaN    NaN    NaN  NaN
1      NaN    pen    1.0  1.0
2      NaN    NaN    NaN  NaN
3      NaN    NaN    NaN  NaN
4      NaN    NaN    NaN  NaN

In [74]:
del frame['new']

In [75]:
frame

item   color  object  price
id                         
0       blue    ball    1.2
1      green     pen    1.0
2     yellow  pencil    0.6
3        red   paper    0.9
4      white     mug    1.7

In [76]:
# There are tons of stuff that we can do with the pandas methods.

### Other Functionalities on Indexes

In [77]:
ser = pd.Series([2,5,7,4], index=['one','two','three','four'])

In [78]:
ser

one      2
two      5
three    7
four     4
dtype: int64

In [79]:
ser.reindex(['three','four','five','one'])

three    7.0
four     4.0
five     NaN
one      2.0
dtype: float64

In [80]:
ser

one      2
two      5
three    7
four     4
dtype: int64

In [81]:
# As you can see from the value returned, the order of the labels has been completely rearranged. The 
# value corresponding to the label ‘two’ has been dropped and a new label ‘five’ is present in the Series.

In [82]:
ser = pd.Series(np.arange(4.), index=['red','blue','yellow','white'])

In [83]:
ser

red       0.0
blue      1.0
yellow    2.0
white     3.0
dtype: float64

In [84]:
ser.drop('yellow')

red      0.0
blue     1.0
white    3.0
dtype: float64

In [85]:
ser.drop(['blue','white'])

red       0.0
yellow    2.0
dtype: float64

In [86]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper'])

In [87]:
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [88]:
frame.drop(['blue','yellow'])

ball  pen  pencil  paper
red       0    1       2      3
white    12   13      14     15

In [89]:
frame.drop(['pen','pencil'],axis=1)

ball  paper
red        0      3
blue       4      7
yellow     8     11
white     12     15

In [90]:
s1 = pd.Series([3,2,5,1],['white','yellow','green','blue'])

In [91]:
s2 = pd.Series([1,4,7,2,1],['white','yellow','black','blue','brown'])

In [92]:
s1

white     3
yellow    2
green     5
blue      1
dtype: int64

In [93]:
s2

white     1
yellow    4
black     7
blue      2
brown     1
dtype: int64

In [94]:
s1 + s2

black     NaN
blue      3.0
brown     NaN
green     NaN
white     4.0
yellow    6.0
dtype: float64

In [95]:
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper'])

In [96]:
frame2 = pd.DataFrame(np.arange(12).reshape((4,3)),
                    index=['blue','green','white','yellow'],
                    columns=['mug','pen','ball'])

In [97]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [98]:
frame2

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [99]:
frame1 + frame2

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [100]:
frame1.add(frame2)

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [101]:
# Operations between DataFrame and Series

In [102]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper'])

In [103]:
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [104]:
ser = pd.Series(np.arange(4), index=['ball','pen','pencil','paper'])

In [105]:
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int32

In [106]:
frame - ser

ball  pen  pencil  paper
red        0    0       0      0
blue       4    4       4      4
yellow     8    8       8      8
white     12   12      12     12

### Function Application and Mapping

In [107]:
#  Functions by Element

In [108]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper'])

In [109]:
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [110]:
np.sqrt(frame)

ball       pen    pencil     paper
red     0.000000  1.000000  1.414214  1.732051
blue    2.000000  2.236068  2.449490  2.645751
yellow  2.828427  3.000000  3.162278  3.316625
white   3.464102  3.605551  3.741657  3.872983

In [111]:
# Functions by Row or Column

In [112]:
f = lambda x: x.max() - x.min()

In [113]:
def f(x):
    return x.max() - x.min()

In [114]:
frame.apply(f)

ball      12
pen       12
pencil    12
paper     12
dtype: int32

In [115]:
frame.apply(f, axis=1)

red       3
blue      3
yellow    3
white     3
dtype: int32

In [116]:
# Function returning a series
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [117]:
frame.apply(f)

ball  pen  pencil  paper
min     0    1       2      3
max    12   13      14     15

In [118]:
# Here we can see the real use of index!
frame.sum()

ball      24
pen       28
pencil    32
paper     36
dtype: int64

In [119]:
frame.mean()

ball      6.0
pen       7.0
pencil    8.0
paper     9.0
dtype: float64

In [120]:
frame.describe()

ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

## Reading and Writing Data

In [121]:
csvframe = pd.read_csv('data01.csv')

In [122]:
csvframe

white  red  blue  green animal
0      1    5     2      3    cat
1      2    7     8      5    dog
2      3    3     6      7  horse
3      2    2     8      3   duck
4      4    4     2      1  mouse

In [123]:
df = pd.read_table("data02.txt", sep=",", skiprows=[0,1,3,6])

In [124]:
df

white  red  blue  green animal
0      1    5     2      3    cat
1      2    7     8      5    dog
2      3    3     6      7  horse
3      2    2     8      3   duck
4      4    4     2      1  mouse

In [125]:
df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>white</th>\n      <th>red</th>\n      <th>blue</th>\n      <th>green</th>\n      <th>animal</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>5</td>\n      <td>2</td>\n      <td>3</td>\n      <td>cat</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>7</td>\n      <td>8</td>\n      <td>5</td>\n      <td>dog</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>3</td>\n      <td>6</td>\n      <td>7</td>\n      <td>horse</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2</td>\n      <td>2</td>\n      <td>8</td>\n      <td>3</td>\n      <td>duck</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>4</td>\n      <td>4</td>\n      <td>2</td>\n      <td>1</td>\n      <td>mouse</td>\n    </tr>\n  </tbody>\n</table>'

In [126]:
# The same can be dumped to a file with .html extension and then use .read_html() method to load it as a pandas dataframe.

In [127]:
# Similarly we can do it for:
# 1. xml using read_xml() and to_xml() methods.
# 2. excel using read_excel() and to_excel() methods.
# 3. json using read_json() and to_json() methods.

## Data Manipulation

### Data Preparation

In [128]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                       'price': [12.33,11.44,33.21,13.23,33.62]})

In [129]:
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [130]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                      'color': ['white','red','red','black']})

In [131]:
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [132]:
pd.merge(frame1, frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [133]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                       'color': ['white','red','red','black','green'],
                       'brand': ['OMG','ABC','ABC','POD','POD']})

In [134]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [135]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                       'brand': ['OMG','POD','ABC','POD']})

In [136]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [137]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [138]:
# When we have multiple columns with same name, we can specify the on option with the column names
pd.merge(frame1, frame2, on="id")

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [139]:
pd.merge(frame1, frame2, on="brand")

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [140]:
frame2.columns = ['sid','brand']

In [141]:
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [142]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [143]:
frame2.columns = ['id','brand']

In [144]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [145]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0  ashtray  green     POD     NaN
1     ball  white     OMG     ABC
2      mug  black     POD     NaN
3      pen    red     ABC     POD
4   pencil    red     ABC     OMG
5   pencil    red     ABC     POD

In [146]:
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [147]:
pd.merge(frame1,frame2,on='id',how='right')

id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

In [148]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [149]:
# Alternatively
frame2.columns = ["id_2", "brand_2"]
frame1.join(frame2)

id  color brand    id_2 brand_2
0     ball  white   OMG  pencil     OMG
1   pencil    red   ABC  pencil     POD
2      pen    red   ABC    ball     ABC
3      mug  black   POD     pen     POD
4  ashtray  green   POD     NaN     NaN

### Concatenating

In [150]:
array1 = np.arange(9).reshape((3,3))

In [151]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
array2 = np.arange(9).reshape((3,3))+6

In [153]:
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [154]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [155]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [156]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])

In [157]:
ser1

1    0.161140
2    0.131006
3    0.627392
4    0.780237
dtype: float64

In [158]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])

In [159]:
ser2

5    0.111306
6    0.542331
7    0.453930
8    0.854311
dtype: float64

In [160]:
pd.concat([ser1, ser2])

1    0.161140
2    0.131006
3    0.627392
4    0.780237
5    0.111306
6    0.542331
7    0.453930
8    0.854311
dtype: float64

In [161]:
pd.concat([ser1, ser2], axis=1)

0         1
1  0.161140       NaN
2  0.131006       NaN
3  0.627392       NaN
4  0.780237       NaN
5       NaN  0.111306
6       NaN  0.542331
7       NaN  0.453930
8       NaN  0.854311

In [162]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.161140
   2    0.131006
   3    0.627392
   4    0.780237
2  5    0.111306
   6    0.542331
   7    0.453930
   8    0.854311
dtype: float64

In [163]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.161140       NaN
2  0.131006       NaN
3  0.627392       NaN
4  0.780237       NaN
5       NaN  0.111306
6       NaN  0.542331
7       NaN  0.453930
8       NaN  0.854311

In [164]:
longframe = pd.DataFrame({ 'color':['white','white','white',
                                   'red','red','red',
                                   'black','black','black'],
                          'item':['ball','pen','mug',
                                  'ball','pen','mug',
                                  'ball','pen','mug'],
                          'value': np.random.rand(9)})

In [165]:
longframe

color  item     value
0  white  ball  0.019976
1  white   pen  0.836856
2  white   mug  0.193367
3    red  ball  0.848961
4    red   pen  0.751745
5    red   mug  0.829002
6  black  ball  0.618320
7  black   pen  0.308102
8  black   mug  0.382867

In [166]:
wideframe = longframe.pivot(index = 'item', columns = 'color')

In [167]:
wideframe

value                    
color     black       red     white
item                               
ball   0.618320  0.848961  0.019976
mug    0.382867  0.829002  0.193367
pen    0.308102  0.751745  0.836856

### Data Transformation

#### Drop Duplicates

In [168]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                      'value': [2,1,3,3,2]})

In [169]:
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [170]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [171]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

#### Replacing Values via Mapping

In [172]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                      'color':['white','rosso','verde','black','yellow'],
                      'price':[5.56,4.20,1.30,0.56,2.75]})

In [173]:
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [174]:
newcolors = {
     'rosso': 'red',
     'verde': 'green'
  }

In [175]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [176]:
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [177]:
# To update it in the original dataframe we either have to use the inplace option or reassign the dataframe.

In [178]:
frame.replace(newcolors, inplace=True)

In [179]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

#### Adding Values via Mapping

In [180]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                      'color':['white','red','green','black','yellow']})

In [181]:
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [182]:
price = {
     'ball' : 5.56,
     'mug' : 4.20,
     'bottle' : 1.30,
     'scissors' : 3.41,
     'pen' : 1.30,
     'pencil' : 0.56,
     'ashtray' : 2.75
  }

In [183]:
frame['price'] = frame['item'].map(price)

In [184]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

### Data Aggregation

#### GroupBy

In [185]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
                      'object': ['pen','pencil','pencil','ashtray','pen'],
                      'price1' : [5.56,4.20,1.30,0.56,2.75],
                      'price2' : [4.75,4.12,1.60,0.75,3.15]})

In [186]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [187]:
group = frame['price1'].groupby(frame['color'])

In [188]:
group

In [189]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [190]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [191]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

#### Hierarchical Grouping

In [192]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])

In [193]:
ggroup

In [194]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [195]:
frame[['price1','price2']].groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [196]:
frame.groupby(frame['color']).groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [197]:
frame.groupby(frame['color']).sum("price1")

price1  price2
color                
green    4.05    4.75
red      4.76    4.87
white    5.56    4.75

In [198]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15