## Ndarray: the heart of the library


In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
a.shape

(3,)

In [7]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [8]:
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [9]:
b.dtype

dtype('float64')

In [10]:
b.shape

(2, 2)

### Create an Array

In [11]:
c = np.array([[1, 2, 3],[4, 5, 6]])

In [12]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
g = np.array([['a', 'b'],['c', 'd']])

In [14]:
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [15]:
# There are other bunch of data types that you can use in the array.

In [16]:
# We can have complex numbers too!!

In [17]:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)

In [18]:
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

###  Intrinsic Creation of an Array

In [19]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(20,100)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# We can press shift+tab together keeping the cursor inside the method to get the information about the method. 
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
 np.random.random(3)

array([0.14144862, 0.12136176, 0.24835748])

## Basic Operation


### Arithmetic Operators

In [27]:
a = np.arange(4)

In [28]:
a

array([0, 1, 2, 3])

In [29]:
a+4

array([4, 5, 6, 7])

In [30]:
a*2

array([0, 2, 4, 6])

In [31]:
b = np.arange(4,8)

In [32]:
b

array([4, 5, 6, 7])

In [33]:
a

array([0, 1, 2, 3])

In [34]:
b

array([4, 5, 6, 7])

In [35]:
a+b

array([ 4,  6,  8, 10])

In [36]:
a-b

array([-4, -4, -4, -4])

In [37]:
a*b

array([ 0,  5, 12, 21])

### The Matrix Product

In [38]:
A = np.arange(0, 9).reshape(3, 3)

In [39]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
B = np.ones((3, 3))

In [41]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [43]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [44]:
# The first element here is the dot product of the first row in array A and first column of array B
(0. * 1) + (1. * 1) + (2. * 1)

3.0

In [45]:
# The 2nd row and 1st element i.e 12 is the result of 2nd row of A and 1st column of B
(3. * 1) + (4. * 1) + (5. * 1)

12.0

### Increment and Decrement Operators

In [46]:
a

array([0, 1, 2, 3])

In [47]:
a += 1

In [48]:
a

array([1, 2, 3, 4])

In [49]:
a -= 1

In [50]:
a

array([0, 1, 2, 3])

### Universal Functions 

In [51]:
# A universal function, generally called ufunc, is a function operating of an array in an element-by-element 
# fashion. This means that it is a function that acts individually on each single element of the input array to 
# generate a corresponding result in a new output array. 

In [52]:
a = np.arange(1,5)

In [53]:
a

array([1, 2, 3, 4])

In [54]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [55]:
a

array([1, 2, 3, 4])

In [56]:
# This is still not modified, all these methods returns a new array

In [57]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [58]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Aggregate Functions

In [59]:
a.sum()

10

In [60]:
a.min()

1

In [61]:
a.max()

4

In [62]:
a.mean()

2.5

In [63]:
a.std()

1.118033988749895

##  Indexing, Slicing, and Iterating

### Indexing

In [64]:
a = np.arange(10, 16)

In [65]:
a

array([10, 11, 12, 13, 14, 15])

In [66]:
# If I want to access the number 12 then we have to access it like this:
a[2]

12

In [67]:
# As we know that the index starts from 0, so we have to use 2 to access the element 12 

In [68]:
# Python also supports reverse indexing where you can give negative values and access it from the last
a[-1]

15

In [69]:
# To select multiple elements
a[[0,1,2]]

array([10, 11, 12])

In [70]:
A = np.arange(10, 19).reshape((3, 3))

In [71]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
A[1,2]

15

In [73]:
A[0][1]

11

### Slicing

In [74]:
a = np.arange(10, 16)

In [75]:
a

array([10, 11, 12, 13, 14, 15])

In [76]:
a[1:5]

array([11, 12, 13, 14])

In [77]:
a[1:5:2]

array([11, 13])

In [78]:
a[::2]

array([10, 12, 14])

In [79]:
A = np.arange(10, 19).reshape((3, 3))

In [80]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [81]:
# This will give only the values of first row in all the columns
A[0,:]

array([10, 11, 12])

In [82]:
# This will give only the values of all the rows in first column
A[:,0]

array([10, 13, 16])

### Iterating an array

In [83]:
for i in a:
    print(i)

10
11
12
13
14
15


In [84]:
for i in A:
    print(i)

[10 11 12]
[13 14 15]
[16 17 18]


In [85]:
for i in A.flat:
    print(i)

10
11
12
13
14
15
16
17
18


In [86]:
A = np.random.random((4, 4))

In [87]:
A

array([[0.83663117, 0.7081079 , 0.07204266, 0.44829847],
       [0.69449068, 0.36605539, 0.10600484, 0.58781134],
       [0.52161681, 0.55466239, 0.01581549, 0.95162423],
       [0.00582876, 0.82683125, 0.20681589, 0.05581117]])

In [88]:
A < 0.5

array([[False, False,  True,  True],
       [False,  True,  True, False],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [89]:
# This will filter out all the values based on the condition
A[A < 0.5]

array([0.07204266, 0.44829847, 0.36605539, 0.10600484, 0.01581549,
       0.00582876, 0.20681589, 0.05581117])

In [90]:
# There are a tons of methods similar to these, and you can do a lot of stuff with those methods.

In [91]:
# Please visit https://numpy.org/doc/stable/user/basics.html and explore!